CREATE TABLE Feedbacks(
[FeedbackId] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[AccountId] UNIQUEIDENTIFIER REFERENCES Accounts(AccountId) NOT NULL,
[ProductId] UNIQUEIDENTIFIER REFERENCES Products(ProductId) NOT NULL,
[Date] DATETIME NOT NULL,
[Text] NTEXT NOT NULL,
[DeleteDt] DATETIME
);
